events {}

http {
  server {
    listen 80;
    server_name jpkaresearch.store www.jpkaresearch.store;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    # API → backend
    location /api/ {
      proxy_pass http://ecprice-backend:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
    }

    # FRONTEND (SPA 핵심)
    location / {
      proxy_pass http://ecprice-frontend:80;
      proxy_set_header Host $host;
      try_files $uri $uri/ /index.html;
    }
  }
}
