spring:
  application:
    name: ecprice-research

  profiles:
    active: aws   # ✅ 반드시 여기

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
