spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/ecprice?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# 운영에서도 키는 env
openai:
  api:
    key: ${OPENAI_API_KEY}
    model: ${OPENAI_API_MODEL}

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}

coupang:
  accessKey: ${COUPANG_ACCESS_KEY}
  secretKey: ${COUPANG_SECRET_KEY}

rakuten:
  api:
    key: ${RAKUTEN_API_KEY}
    secret: ${RAKUTEN_API_SECRET}
    affiliate: ${RAKUTEN_AFFILIATE_ID}
    apiUrl: "https://app.rakuten.co.jp/services/api/IchibaItem/Search/20220601"

scraperapi:
  api:
    key: ${SCRAPER_API_KEY}

exchange:
  api:
    key: ${EXCHANGE_API_KEY}
  url:
    live: "https://api.exchangerate.host/live"
    convert: "https://api.exchangerate.host/convert"
    list: "https://api.exchangerate.host/list"
    historical: "https://api.exchangerate.host/historical"

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ecprice-research

google:
  oauth:
    clientId: ${GOOGLE_OAUTH_CLIENT_ID}
    clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    redirectUri: "https://jpkaresearch.store/login/oauth2/code/google"
    scope:
      - profile
      - email
cors:
  allowed-origins: https://jpkaresearch.store
