spring:
  application:
    name: ecprice-research
    profiles:
      active: aws

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}